config/routes.rb
Rails.application.routes.draw do

  resources :inspections do

    resources :elements do
      collection do
        post :save_quantity_changes
      end

      member do
        get :edit_comment
      end

      resources :child_elements
      resources :defects do
        member do
          get :edit_comment
        end

        resources :images
        resources :defect_locations
      end

      resources :images
    end

    resources :images

    collection do
      get 'reset'
      post 'new_search'
      get 'inspection_type_settings'
      get 'audit_export'
      get 'nbi_export'
      get 'nbe_export'
      get 'qa_qc_export'

      post 'change_inspectors'
    end

    member do
      get 'edit_inspectors'
      get 'allowed_to_finalize'
      get 'print'
    end
  end

  resources :streambed_profiles do
    resources :streambed_profile_points

    collection do
      put 'update_many'
    end
  end

  resources :roadways

  resources :roadbeds do
    member do
      post :save_vertical_clearance_changes
    end
  end
  resources :roadbed_lines, only: [:index]

  resources :processable_uploads, only: [:index, :create, :destroy] do
    member do
      get 'process_file'
    end
  end

  # JSON API #
  namespace :api do
    namespace :v1 do
      get 'reference_data' => 'references#index'
      get 'associations' => 'associations#index'
      get 'bridge_conditions' => 'bridge_conditions#index'
      get 'elements' => 'elements#index'
      get 'defects' => 'defects#index'
      get 'defect_definitions' => 'defect_definitions#index'
      get 'element_definitions' => 'element_definitions#index'

      resources :inspections, only: [:index, :update] do
        resources :images
        resources :documents
      end

      resources :bridges
      resources :culverts
      resources :highway_structures, except: [:index, :update]
      resources :highway_structures, only: [:index, :update] do
        resources :images
        resources :documents
      end
      resources :streambed_profiles

      resources :elements, only: [:index, :update] do
        resources :images
      end
      resources :defects, only: [:index, :update] do
        resources :images
      end
    end
  end

  resources :highway_maps, :only => [] do
    collection do
      get 'map'
      get 'table'
    end
  end
end

app/models/roadbed_line.rb
class RoadbedLine < ApplicationRecord
  include TransamObjectKey
  has_paper_trail

  belongs_to :roadbed
  belongs_to :inspection

  scope :lines, -> { where.not(number: ['L', 'R']).order(:number) }
  scope :by_inspection, -> (inspection) { where(inspection: inspection) }

  def self.allowable_params
    [
      :entry,
      :exit,
      :minimum_clearance
    ]
  end

  def has_no_restrictions?
    roadbed.use_minimum_clearance? ? minimum_clearance.nil? : (entry.nil? && exit.nil?)
  end

  def not_applicable?
    roadbed.use_minimum_clearance? ? minimum_clearance.zero? : (entry.zero? && exit.zero?)
  end
end

app/controllers/api/v1/roadbed_lines_controller.rb
class Api::V1::RoadbedLinesController < Api::ApiController
  before_action :query_roadbed_lines

  # GET /roadbed_lines
  def index
  end

  private

  def query_roadbed_lines
    inspection = Inspection.find_by_guid(params[:inspection_id])
    if !inspection
      @status = :fail
      @data = {structure: "Inspection should be provided."}
      render status: :not_found, json: json_response(:fail, data: @data)
    end

    @roadbeds = Roadbed.where(inspection: inspection)
  end

end

app/controllers/roadbed_lines_controller.rb
class RoadbedLinesController < TransamController
  def index
    @roadbed = Roadbed.find_by_object_key(params[:roadbed_id])
    @inspection = Inspection.find_by_object_key(params[:inspection_id])
  end
end

app/views/roadbed_lines/_roadbed_line_cell.html.haml
- val = line&.send(number_type)
%td.center.roadbed-line-cell{data: {line_id: line&.id, line_type: line_type, number_type: number_type}}
  %span.number-display
    = val ? (val == 0 ? 'N/A' : val) : 'No Restrictions'
  %span.number-edit{style: 'display: none;'}
    %input.number-input.form-control{type: 'number', min: 0, value: val}

app/views/roadbed_lines/_roadbed_lines_table.html.haml
:css
  #roadbed-lines-table .number-input {
    width: 80px !important;
  }

%table.table.table-bordered#roadbed-lines-table
  - if roadbed
    %thead
      %tr
        %th.center Location
        %th.center
          = "L"
          = select_tag "#{roadbed.left_edge&.id}_roadbed_line_toggle".to_sym, options_for_select([['No Restrictions', nil], ['N/A', 0], ['Value', 1]], roadbed.left_edge&.has_no_restrictions? ? nil : (roadbed.left_edge&.not_applicable? ? 0 : 1)), class: 'form-control roadbed_line_toggle', disabled: true

        - roadbed.roadbed_lines.by_inspection(@inspection.try(:inspection) || @inspection).lines.each do |l|
          %th.center
            = l.number
            = select_tag "#{l.id}_roadbed_line_toggle".to_sym, options_for_select([['No Restrictions', nil], ['N/A', 0], ['Value', 1]], l.has_no_restrictions? ? nil : (l.not_applicable? ? 0 : 1)), class: 'form-control roadbed_line_toggle', disabled: true
        %th.center
          = "R"
          = select_tag "#{roadbed.right_edge&.id}_roadbed_line_toggle".to_sym, options_for_select([['No Restrictions', nil], ['N/A', 0], ['Value', 1]], roadbed.right_edge&.has_no_restrictions? ? nil : (roadbed.right_edge&.not_applicable? ? 0 : 1)), class: 'form-control roadbed_line_toggle', disabled: true
    %tbody
      - if roadbed.use_minimum_clearance?
        %tr{data: {type: 'minimum_clearance'}}
          %td Minimum Clearance
          = render 'roadbed_lines/roadbed_line_cell', line: roadbed.left_edge, line_type: 'left_edge', number_type: 'minimum_clearance'


          - roadbed.roadbed_lines.by_inspection(@inspection.try(:inspection) || @inspection).lines.each do |l|
            = render 'roadbed_lines/roadbed_line_cell', line: l, line_type: 'line', number_type: 'minimum_clearance'

          = render 'roadbed_lines/roadbed_line_cell', line: roadbed.right_edge, line_type: 'right_edge', number_type: 'minimum_clearance'
      - else
        %tr{data: {type: 'entry'}}
          %td Entry
          = render 'roadbed_lines/roadbed_line_cell', line: roadbed.left_edge, line_type: 'left_edge', number_type: 'entry'


          - roadbed.roadbed_lines.by_inspection(@inspection.try(:inspection) || @inspection).lines.each do |l|
            = render 'roadbed_lines/roadbed_line_cell', line: l, line_type: 'line', number_type: 'entry'

          = render 'roadbed_lines/roadbed_line_cell', line: roadbed.right_edge, line_type: 'right_edge', number_type: 'entry'
        %tr{data: {type: 'exit'}}
          %td Exit
          = render 'roadbed_lines/roadbed_line_cell', line: roadbed.left_edge, line_type: 'left_edge', number_type: 'exit'

          - roadbed.roadbed_lines.by_inspection(@inspection.try(:inspection) || @inspection).lines.each do |l|
            = render 'roadbed_lines/roadbed_line_cell', line: l, line_type: 'line', number_type: 'exit'

          = render 'roadbed_lines/roadbed_line_cell', line: roadbed.right_edge, line_type: 'right_edge', number_type: 'exit'

- if roadbed
  :javascript
    $(".roadbed_line_toggle").change(function() {
      var roadbed_line_id = $(this).attr('id').split('_')[0];
      var cells = $('td[data-line-id="'+roadbed_line_id+'"] input');

      if (parseInt($(this).val()) == 1) {
        if (parseInt(cells.first().val()) == 0) {
          cells.val('');
        }
        cells.attr('disabled', false);
      } else {
        cells.val($(this).val());
        cells.attr('disabled', true);
      }
    });

    function is_vc_form_valid() {
      //TODO: add form validations
      return true;
    }

    function get_vc_changes() {
      if(!is_vc_editing_enabled()) {
        return null;
      }

      var changes = {};

      $('.roadbed-line-cell').each(function(idx, cell) {
        var line_id = $(cell).attr('data-line-id');
        if(!line_id) {
          return;
        }
        if(!changes[line_id]) {
          changes[line_id] = {};
        }

        var number_type = $(cell).attr('data-number-type');
        var val = $(cell).find('.number-input').val();
        changes[line_id][number_type] = val;
      });
      return changes;
    }

    function submit_vc_changes() {
      if(is_vc_form_valid()) {
        $("#spinner").show();

        $('input').attr('disabled', false); // undisable all inputs so they're submitted

        $.ajax({
          url: "#{save_vertical_clearance_changes_roadbed_path(roadbed&.object_key)}",
          method: 'post',
          data: {
            vertical_clearance_changes: get_vc_changes()
          },
          success: function() {
            console.log('vercial clearance values save success');
            $("#spinner").hide();
            var current_url = window.location.href;
            if(current_url.includes('restore_roadbed_line_selection')) {
              window.location.reload();
            } else {
              // pass restore_roadbed_line_selection param so to restore current dropdown selections
              // after saving the values
              if(!current_url.includes('?')) {
                current_url += '?';
              }
              current_url += "restore_roadbed_line_selection=true";
              window.location.href = current_url;
            }
          },
          failure: function() {
            $("#spinner").hide();
            alert('An error occurred saving the changes. Please try again.');
          }
        });
      }
    }

    $(function() {
      if(is_vc_editing_enabled()) {
        enable_vc_editing();
      }

      $( window ).unload(function() {
        cache_roadbed_line_selection();
      });

      if(#{params[:restore_roadbed_line_selection] == 'true' || false}) {
        restore_roadbed_line_selection();
      }
    });

app/views/roadbed_lines/index.js.haml
$('#roadbed-lines-table').replaceWith("#{escape_javascript(render 'roadbed_lines/roadbed_lines_table', roadbed: @roadbed)}");