config/routes.rb
Rails.application.routes.draw do

  resources :inspections do

    resources :elements do
      collection do
        post :save_quantity_changes
      end

      member do
        get :edit_comment
      end

      resources :child_elements
      resources :defects do
        member do
          get :edit_comment
        end

        resources :images
        resources :defect_locations
      end

      resources :images
    end

    resources :images

    collection do
      get 'reset'
      post 'new_search'
      get 'inspection_type_settings'
      get 'audit_export'
      get 'nbi_export'
      get 'nbe_export'
      get 'qa_qc_export'

      post 'change_inspectors'
    end

    member do
      get 'edit_inspectors'
      get 'allowed_to_finalize'
      get 'print'
    end
  end

  resources :streambed_profiles do
    resources :streambed_profile_points

    collection do
      put 'update_many'
    end
  end

  resources :roadways

  resources :roadbeds do
    member do
      post :save_vertical_clearance_changes
    end
  end
  resources :roadbed_lines, only: [:index]

  resources :processable_uploads, only: [:index, :create, :destroy] do
    member do
      get 'process_file'
    end
  end

  # JSON API #
  namespace :api do
    namespace :v1 do
      get 'reference_data' => 'references#index'
      get 'associations' => 'associations#index'
      get 'bridge_conditions' => 'bridge_conditions#index'
      get 'elements' => 'elements#index'
      get 'defects' => 'defects#index'
      get 'defect_definitions' => 'defect_definitions#index'
      get 'element_definitions' => 'element_definitions#index'

      resources :inspections, only: [:index, :update] do
        resources :images
        resources :documents
      end

      resources :bridges
      resources :culverts
      resources :highway_structures, except: [:index, :update]
      resources :highway_structures, only: [:index, :update] do
        resources :images
        resources :documents
      end
      resources :streambed_profiles

      resources :elements, only: [:index, :update] do
        resources :images
      end
      resources :defects, only: [:index, :update] do
        resources :images
      end
    end
  end

  resources :highway_maps, :only => [] do
    collection do
      get 'map'
      get 'table'
    end
  end
end

app/models/bridge_like.rb
class BridgeLike < TransamAssetRecord

  has_paper_trail

  acts_as :highway_structure, as: :highway_structurible

  belongs_to :main_span_material_type, class_name: 'StructureMaterialType'
  belongs_to :main_span_design_construction_type, class_name: 'DesignConstructionType'
  belongs_to :approach_spans_material_type, class_name: 'StructureMaterialType'
  belongs_to :approach_spans_design_construction_type, class_name: 'DesignConstructionType'

  belongs_to :strahnet_designation_type
  belongs_to :service_on_type
  belongs_to :service_under_type
  belongs_to :bridge_toll_type
  belongs_to :design_load_type
  belongs_to :operating_rating_method_type, class_name: 'LoadRatingMethodType'
  belongs_to :inventory_rating_method_type, class_name: 'LoadRatingMethodType'
  belongs_to :bridge_posting_type
  belongs_to :vertical_reference_feature_below, class_name: 'ReferenceFeatureType'
  belongs_to :lateral_reference_feature_below, class_name: 'ReferenceFeatureType'
  belongs_to :median_type

  has_many :streambed_profiles, foreign_key: :transam_asset_id

  has_many :bridge_like_conditions, through: :inspections, source: :inspectionible, source_type: 'BridgeLikeCondition'


  FORM_PARAMS = [
    :main_span_material_type_id,
    :main_span_design_construction_type_id,
    :approach_spans_material_type_id,
    :approach_spans_design_construction_type_id,
    :num_spans_main,
    :num_spans_approach,
    :border_bridge_state,
    :border_bridge_pcnt_responsibility,
    :border_bridge_structure_number,
    :strahnet_designation_type_id,
    :deck_structure_type_id,
    :wearing_surface_type_id,
    :membrane_type_id,
    :deck_protection_type_id,
    :service_on_type_id,
    :service_under_type_id,
    :bridge_toll_type_id,
    :max_span_length,
    :left_curb_sidewalk_width,
    :right_curb_sidewalk_width,
    :roadway_width,
    :deck_width,
    :min_vertical_clearance_above,
    :vertical_reference_feature_below_id,
    :min_vertical_clearance_below,
    :lateral_reference_feature_below_id,
    :min_lateral_clearance_below_right,
    :min_lateral_clearance_below_left,
    :design_load_type_id,
    :operating_rating_method_type_id,
    :operating_rating,
    :inventory_rating_method_type_id,
    :inventory_rating,
    :bridge_posting_type_id,
    # AncillaryStructure, because not acts_as
    :mast_arm_frame_type_id,
    :column_type_id,
    :foundation_type_id,
    :upper_connection_type_id,
    :maintenance_patrol
  ]

  CLEANSABLE_FIELDS = [

  ]

  SEARCHABLE_FIELDS = [

  ]

  RATING_PARAMS = [:design_load_type_id, :operating_rating_method_type_id, :operating_rating, :inventory_rating_method_type_id, :inventory_rating, :bridge_posting_type_id]

  INSPECTOR_PARAMS = [:max_span_length, :left_curb_sidewalk_width, :right_curb_sidewalk_width, :roadway_width, :deck_width, :min_lateral_clearance_below_right, :min_lateral_clearance_below_left,:num_spans_main, :num_spans_approach,:deck_structure_type_id, :wearing_surface_type_id, :membrane_type_id, :deck_protection_type_id,]

  NDIGITS = 3

  #-----------------------------------------------------------------------------
  #
  # Class Methods
  #
  #-----------------------------------------------------------------------------

  def self.inspection_types
    InspectionType.all
  end

  def self.default_map_renderer_attr
    :calculated_condition
  end

  def self.process_upload(io, ext, &block)
    unless ['.xml', '.zip'].include? ext
      return false, "Extension #{ext} should be .xml or .zip"
    end
    successful = true
    msg = ''
    class_name = nil

    if ext == '.zip'
      #
    else
      begin
        successful, msg, class_name = create_or_update_from_xml(io, &block)
      rescue TypeError, NoMethodError => e
        if Rails.env.sandbox?
          Rails.logger.warn e.message
          Rails.logger.warn e.backtrace.join("/n")
          return false, e.message
        else
          raise
        end
      end
    end
    return successful, msg, class_name
  end

  # NOTE: this is woefully out of date but not yet completely removed.
  def self.create_or_update_from_xml(io, &block)
    return false, "Not implemented", nil
  end # create_or_update_from_xml

  def self.process_roadway(hash, bridgelike)
    # Validate ON_UNDER
    on_under = hash['ON_UNDER']
    return unless (on_under.size == 1) && (/[12A-Z]/ =~ on_under)

    vclrinv = hash['VCLRINV']&.to_f
    # It appears that 99.9 feet is also entered to indicate no restrictions
    min_vertical_clearance = (vclrinv.nil? || vclrinv > 30.0) ? nil :
                               Uom.convert(vclrinv, Uom::METER, Uom::FEET).round(NDIGITS)
    Roadway.new(
      highway_structure: bridgelike,
      on_under_indicator: on_under,
      route_signing_prefix: RouteSigningPrefix.find_by(code: hash['KIND_HWY']),
      service_level_type: ServiceLevelType.find_by(code: hash['LEVL_SRVC']),
      route_number: hash['ROUTENUM'],
      features_intersected: on_under == '1' ? bridgelike.features_intersected : bridgelike.facility_carried,
      facility_carried: on_under == '1' ? bridgelike.facility_carried : bridgelike.features_intersected,
      min_vertical_clearance: min_vertical_clearance,
      on_base_network: hash['ONBASENET'] == '1',
      lrs_route: hash['LRSINVRT'],
      lrs_subroute: hash['SUBRTNUM'],
      functional_class: FunctionalClass.find_by(code: hash['FUNCCLASS']),
      lanes: hash['LANES'].to_i,
      average_daily_traffic: hash['ADTTOTAL'].to_i,
      average_daily_traffic_year: hash['ADTYEAR'].to_i,
      total_horizontal_clearance: Uom.convert(hash['HCLRINV'].to_f, Uom::METER, Uom::FEET).round(NDIGITS),
      traffic_direction_type: TrafficDirectionType.find_by(code: hash['TRAFFICDIR']),
      on_national_highway_system: hash['NHS_IND'] == '1',
      average_daily_truck_traffic_percent: hash['TRUCKPCT'].to_i,
      on_truck_network: hash['TRUCKNET'] == '1',
      future_average_daily_traffic: hash['ADTFUTURE'].to_i,
      future_average_daily_traffic_year: hash['ADTFUTYEAR'].to_i,
      strahnet_designation_type: StrahnetDesignationType.find_by(code: hash['DEFHWY']),
      federal_lands_highway_type: FederalLandsHighwayType.find_by(code: hash['FEDLANDHWY']) ||
                FederalLandsHighwayType.find_by(code: '0'),
      detour_length: Uom.convert([hash['BYPASSLEN'].to_f, 0.0].max, Uom::KILOMETER, Uom::MILE).round(NDIGITS)
    )
  end


  def self.process_inspection(hash, struct_class_code, date, error_stats)
    type, desc, inspection_frequency = get_inspection_type(hash['INSPTYPE'], hash)

    unless type
      error_stats[:no_inspection_type] += 1
      raise EncodingError.new "No inspection type found for INSPTYPE: #{hash['INSPTYPE']}."
    end

    inspection_klass = case struct_class_code
    when 'BRIDGE', 'MISCELLANEOUS'
      BridgeCondition
    when 'CULVERT'
      CulvertCondition
    end

    PaperTrail.request.enable_model(Inspection)
    inspection = inspection_klass.new(event_datetime: date, calculated_inspection_due_date: date,
                                      inspection_frequency: inspection_frequency,
                                      inspection_type: type, description: desc,
                                      notes: hash['NOTES'], state: 'final')
    PaperTrail.request.disable_model(Inspection)

    # safety ratings
    {railings_safety_type_id: 'RAILRATING',
     transitions_safety_type_id: 'TRANSRATIN',
     approach_rail_safety_type_id: 'ARAILRATIN',
     approach_rail_end_safety_type_id: 'AENDRATING'}.each do |attribute, key|
      inspection[attribute] = FeatureSafetyType.where(code: hash[key]).pluck(:id).first
    end

    inspection.operational_status_type = OperationalStatusType.find_by(code: hash['OPPOSTCL'])
    inspection.channel_condition_type = ChannelConditionType.find_by(code: hash['CHANRATING'])
    inspection.scour_critical_bridge_type = ScourCriticalBridgeType.find_by(code: hash['SCOURCRIT'])

    if struct_class_code == 'BRIDGE' || struct_class_code == 'MISCELLANEOUS'
      # condition ratings
      {deck_condition_rating_type_id: 'DKRATING',
       superstructure_condition_rating_type_id: 'SUPRATING',
       substructure_condition_rating_type_id: 'SUBRATING'}.each do |attribute, key|
        inspection[attribute] = BridgeConditionRatingType.where(code: hash[key]).pluck(:id).first
      end

      inspection.underclearance_appraisal_rating_type_id = BridgeAppraisalRatingType.where(code: hash['UNDERCLR']).pluck(:id).first
    else # Culvert
      inspection.culvert_condition_type_id = CulvertConditionType.where(code: hash['CULVRATING']).pluck(:id).first
    end

    # appraisal ratings
    {structural_appraisal_rating_type_id: 'STRRATING',
     deck_geometry_appraisal_rating_type_id: 'DECKGEOM',
     waterway_appraisal_rating_type_id: 'WATERADEQ',
     approach_alignment_appraisal_rating_type_id: 'APPRALIGN'}.each do |attribute, key|
      inspection[attribute] = BridgeAppraisalRatingType.where(code: hash[key]).pluck(:id).first
    end

    inspection.save!
    inspection
  end

  def self.get_inspection_type(type_code, hash)
    frequency = hash['BRINSPFREQ']

    # Map from BrM inspection types to SIMSA type
    case type_code
    # special
    when 'L', 'M', 'O', '4', '5'
      type = InspectionType.find_by(name: 'Special')
      case type_code
      when 'L'
        desc = 'Accident Damage (traffic)'
      when 'M'
        desc = 'Natural Disaster Damage'
      when 'O', '4', '5'
        desc = 'Other'
      end
      frequency = hash['OSINSPFREQ']
    when 'B', 'C', 'D', 'E'
      type = InspectionType.find_by(name: 'Underwater')
      frequency = hash['UWINSPFREQ']
    when 'G'
      type = InspectionType.find_by(name: 'Fracture Critical')
      frequency = hash['FCINSPFREQ']
    else
      type = InspectionType.find_by(code: type_code)
    end
    return type, desc, frequency
  end

  # Convert units if needed and round values
  def self.process_quantities(value, target_units)
    case target_units
    when 'sq feet'

app/models/highway_structure_type.rb
class HighwayStructureType < ApplicationRecord
  # All types that are available
  scope :active, -> { where(:active => true) }

  def to_s
    name
  end
end

app/controllers/api/v1/highway_structures_controller.rb
class Api::V1::HighwayStructuresController < Api::ApiController
  before_action :set_highway_structure, only: [:show, :update, :destroy]
  
  # GET /highway_structures.json
  def index
    total_highway_structures = get_highway_structures
    @highway_structures = paginate total_highway_structures.page(params[:page]).per(params[:page_size])
  end

  # GET /highway_structures/1.json
  def show 
  end

  # POST /highway_structures.json
  def create
    @highway_structure = HighwayStructure.new(form_params)
    unless @highway_structure.save
      @status = :fail
      @message  = "Unable to upload highway structure due to the following error: #{@highway_structure.errors.messages}" 
      render status: 400, json: json_response(:fail, message: @message)
    end
  end

  # PATCH/PUT /highway_structures/1.json
  def update
    unless @highway_structure.update(form_params)
      @status = :fail
      @message  = "Unable to update highway structure due to the following error: #{@highway_structure.errors.messages}" 
      render status: 400, json: json_response(:fail, message: @message)
    end
  end

  # DELETE /highway_structures/1.json
  def destroy
    unless @highway_structure.destroy
      @status = :fail
      @message  = "Unable to destroy highway structure due to the following error: #{@highway_structure.errors.messages}" 
      render status: 400, json: json_response(:fail, message: @message)
    end
  end

  private

  def get_highway_structures
    # TODO: filtering
    HighwayStructure.all
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_highway_structure
    @highway_structure = HighwayStructure.find_by(:object_key => params[:id])

    unless @highway_structure
      @status = :fail
      @data = {id: "Highway structure #{params[:id]} not found."}
      render status: :not_found, json: json_response(:fail, data: @data)
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def form_params
    params.require(:highway_structure).permit(HighwayStructure.new.allowable_params)
  end

end

app/views/highway_structures/bridge_like/_age_service_form.html.haml
= editable_asset_field_tag(asset, :manufacture_year, reference_label('highway_structures', 'transam_assets.manufacture_year', 'Year Built'), type: 'number', required: false, min: get_system_asset_starting_year, max: Date.today.year)
= editable_asset_field_tag(asset, :lanes_on, reference_label('highway_structures', 'lanes_on', 'Lanes On'), required: false) unless @sshml
= editable_asset_field_tag(asset, :lanes_under, reference_label('highway_structures', 'lanes_under', 'Lanes Under'), required: false)
= editable_asset_association_tag(asset, :service_on_type, reference_label('bridges', 'service_on_type_id', 'Service Type On'), include_blank: true) unless @sshml
= editable_asset_association_tag(asset, :service_under_type, reference_label('bridges', 'service_under_type_id', 'Service Type Under'), include_blank: true)

app/views/highway_structures/bridge_like/_appraisal_form.html.haml
- if @sshml
  = render 'highway_structures/bridge_like/sshml/appraisal_form'
- else
  .form-group
    %label.control-label
      = reference_label('bridge_conditions', 'railings_safety_type_id', 'Bridge Rail')
    .display-value
      = @latest_condition&.railings_safety_type
  .form-group
    %label.control-label
      = reference_label('bridge_conditions', 'transitions_safety_type_id', 'Transitions')
    .display-value
      = @latest_condition&.transitions_safety_type
  .form-group
    %label.control-label
      = reference_label('bridge_conditions', 'approach_rail_safety_type_id', 'Approach Guardrail')
    .display-value
      = @latest_condition&.approach_rail_safety_type
  .form-group
    %label.control-label
      = reference_label('bridge_conditions', 'approach_rail_end_safety_type_id', 'End Treatments')
    .display-value
      = @latest_condition&.approach_rail_end_safety_type
  .form-group
    %label.control-label
      = reference_label('bridge_conditions', 'structural_appraisal_rating_type_id', 'Structural Evaluation')
    .display-value
      = @latest_condition&.structural_appraisal_rating_type
  .form-group
    %label.control-label
      = reference_label('bridge_conditions', 'deck_geometry_appraisal_rating_type_id', 'Deck Geometry')
    .display-value
      = @latest_condition&.deck_geometry_appraisal_rating_type
  - if ['Bridge', 'MiscStructure'].include? @asset_class_name
    .form-group
      %label.control-label
        = reference_label('bridge_conditions', 'underclearance_appraisal_rating_type_id', 'Underclearances Appraisal')
      .display-value
        = @latest_condition&.underclearance_appraisal_rating_type
  .form-group
    %label.control-label
      = reference_label('bridge_conditions', 'waterway_appraisal_rating_type_id', 'Waterway Adequacy')
    .display-value
      = @latest_condition&.waterway_appraisal_rating_type
  .form-group
    %label.control-label
      = reference_label('bridge_conditions', 'approach_alignment_appraisal_rating_type_id', 'Approach Roadway Alignment')
    .display-value
      = @latest_condition&.approach_alignment_appraisal_rating_type
  .form-group
    %label.control-label
      = reference_label('bridge_conditions', 'scour_critical_bridge_type_id', 'Scour Critical')
    .display-value
      = @latest_condition&.scour_critical_bridge_type

app/views/highway_structures/bridge_like/_classification_form.html.haml
= editable_asset_association_tag(asset, :bridge_toll_type, reference_label('bridges', 'bridge_toll_type_id', 'Toll'), include_blank: true) unless @sshml
= editable_asset_association_tag(asset, :maintenance_responsibility, reference_label('highway_structures', 'maintenance_responsibility_id', 'Maintenance Responsibility'), StructureAgentType.active.order(:code).collect{|sat| [sat.id, sat.to_s]}, include_blank: true)
= editable_asset_association_tag(asset, :owner, reference_label('highway_structures', 'owner_id', 'Owner'), StructureAgentType.active.order(:code).map{|sat| [sat.id, sat.to_s]}, include_blank: true)
= editable_asset_association_tag(asset, :structure_status_type, reference_label('highway_structures', 'structure_status_type_id', 'Structure Status'), include_blank: false)
.form-group
  %label.control-label
    = reference_label('highway_structures', 'highway_structurible_type', 'Structure Class')
  .display-value
    = asset.class.name
= editable_asset_association_tag(asset, :historical_significance_type, reference_label('highway_structures', 'historical_significance_type_id', 'Historical Significance'), include_blank: true)
= editable_asset_field_tag(asset, :is_temporary, reference_label('highway_structures', 'is_temporary', 'Temporary Structure'), type: 'boolean')

app/views/highway_structures/bridge_like/_condition_form.html.haml
- if ['Bridge', 'MiscStructure'].include? @asset_class_name
  .form-group
    %label.control-label
      = reference_label('bridge_conditions', 'deck_condition_rating_type_id', 'Deck')
    .display-value
      = @latest_condition&.deck_condition_rating_type
  .form-group
    %label.control-label
      = reference_label('bridge_conditions', 'superstructure_condition_rating_type_id', 'Superstructure')
    .display-value
      = @latest_condition&.superstructure_condition_rating_type
  .form-group
    %label.control-label
      = reference_label('bridge_conditions', 'substructure_condition_rating_type_id', 'Substructure')
    .display-value
      = @latest_condition&.substructure_condition_rating_type
  .form-group
    %label.control-label
      = reference_label('bridge_conditions', 'channel_condition_type_id', 'Channel Protection')
    .display-value
      = @latest_condition&.channel_condition_type
- elsif @asset_class_name == 'Culvert'
  .form-group
    %label.control-label
      = reference_label('culvert_conditions', 'culvert_condition_type_id', 'Culvert Condition')
    .display-value
      = @latest_condition&.culvert_condition_type
- elsif @sshml
  .form-group
    %label.control-label
      = reference_label((@asset_class_name == 'MiscStructure' ? 'misc_conditions' : 'ancillary_conditions'), 'ancillary_condition_type_id', 'SSHML Rating')
    .display-value
      = @latest_condition&.ancillary_condition_type
.form-group
  %label.control-label
    = reference_label('highway_structures', 'calculated_condition', 'Overall Condition')
  .display-value
    = @latest_condition&.calculated_condition&.titleize

app/views/highway_structures/bridge_like/_geometric_data_form.html.haml
- if @sshml
  = render partial: 'highway_structures/bridge_like/sshml/geometric_data_form', locals: {asset: asset}
- else
  = editable_asset_field_tag(asset, :approach_roadway_width, reference_label('highway_structures', 'approach_roadway_width', 'Approach Roadway Width'), required: false)
  = editable_asset_field_tag(asset, :max_span_length, reference_label('bridges', 'max_span_length', 'Maximum Span Length'), required: false)
  = editable_asset_field_tag(asset, :length, reference_label('bridges', 'length', 'Length'), required: false)
  = editable_asset_field_tag(asset, :left_curb_sidewalk_width, reference_label('bridges', 'left_curb_sidewalk_width', 'Left Curb or Sidewalk'), required: false)
  = editable_asset_field_tag(asset, :right_curb_sidewalk_width, reference_label('bridges', 'right_curb_sidewalk_width', 'Right Curb or Sidewalk'), required: false)
  = editable_asset_field_tag(asset, :roadway_width, reference_label('bridges', 'roadway_width', 'Curb to Curb'), required: false)
  = editable_asset_field_tag(asset, :deck_width, reference_label('bridges', 'deck_width', 'Out to Out'), required: false)
  = editable_asset_field_tag(asset, :min_vertical_clearance_above, reference_label('bridges', 'min_vertical_clearance_above', 'Minimum Vertical Clearance Above Bridge'), required: false)
  = editable_asset_association_tag(asset, :vertical_reference_feature_below, reference_label('bridges', 'vertical_reference_feature_below_id', 'Reference Vertical Feature Below Bridge'), include_blank: true)
  = editable_asset_field_tag(asset, :min_vertical_clearance_below, reference_label('bridges', 'min_vertical_clearance_below', 'Minimum Vertical Clearance Below Bridge'), required: false)
  = editable_asset_association_tag(asset, :lateral_reference_feature_below, reference_label('bridges', 'lateral_reference_feature_below_id', 'Reference Horizontal Feature Below Bridge'), include_blank: true)
  = editable_asset_field_tag(asset, :min_lateral_clearance_below_right, reference_label('bridges', 'min_lateral_clearance_below_right', 'Minimum Horizontal Clearance Below Bridge on Right '), required: false)
  = editable_asset_field_tag(asset, :min_lateral_clearance_below_left, reference_label('bridges', 'min_lateral_clearance_below_left', 'Minimum Horizontal Clearance Below Bridge on Left'), required: false)

app/views/highway_structures/bridge_like/_roadways_form.html.haml
= render partial: 'inspections/roadways', locals: {highway_structure: asset, skip_legend: true, roadways: (@asset.assigned_version ? @asset.assigned_version_roadways : @asset.roadways)}

app/views/highway_structures/bridge_like/_summary.html.haml
:css
  .carousel .item {
    height: 225px;
  }

  .carousel .item img {
    position: absolute;
    top: 0;
    left: 0;
    min-width: 100%;
    height: 225px;
  }
.col-sm-4
  .form-group
    %label.control-label= reference_label('highway_structures', 'route_number', '&nbsp')
    .display-value= @asset.route_number
  .form-group
    %label.control-label= reference_label('highway_structures', 'milepoint', 'Milepoint')
    .display-value= @asset.milepoint
  .form-group
    %label.control-label= reference_label('highway_structures', 'city', '* City')
    .display-value= @asset.city
  .form-group
    %label.control-label= reference_label('highway_structures', 'county', 'County')
    .display-value= @asset.county

  .form-group
    %label.control-label= reference_label('highway_structures', 'maintenance_responsibility_id', 'Maintenance Responsibility')
    .display-value= @asset.maintenance_responsibility

  .form-group
    %label.control-label= reference_label('highway_structures', 'owner_id', 'Organization')
    .display-value= @asset.owner

  .form-group
    %label.control-label Suffiency Rating
    .display-value PENDING

.col-sm-4
  .form-group
    %label.control-label= reference_label('highway_structures', 'calculated_condition', 'Overall Condition')
    .display-value= @asset.calculated_condition ? (@asset.inspections.any? ? link_to(@asset.calculated_condition&.titleize, inspection_path(@asset.inspections.ordered.first)) : @asset.calculated_condition) : ''
  - unless @sshml
    .form-group
      %label.control-label= reference_label('bridge_conditions', 'scour_critical_bridge_type_id', 'Scour Critical Bridge')
      .display-value= @latest_condition.try(:scour_critical_bridge_type)
    .form-group
      %label.control-label= reference_label('bridges', 'transam_assets.asset_subtype_id', 'Bridge Type')
      .display-value= @asset.asset_subtype

  .form-group
    %label.control-label= reference_label('highway_structures', 'highway_structure_type_id', 'Structure Type')
    .display-value= @asset.highway_structure_type
  .form-group
    %label.control-label= reference_label('highway_structures', 'inspection_program_id', 'Inspection Program')
    .display-value= @asset.inspection_program

  .form-group
    %label.control-label= reference_label('inspection_type_settings', 'routine_inspection_date', 'Routine Inspection Date')
    .display-value= format_as_date(@asset.inspection_date)
  .form-group
    %label.control-label= reference_label('highway_structures', 'next_inspection_date', 'Next Routine Inspection')
    - calculated_inspection_due_date = @asset.active_inspection&.calculated_inspection_due_date
    .display-value= calculated_inspection_due_date.strftime('%B %Y') if calculated_inspection_due_date.present?

.col-sm-4
  - asset_images = Image.joins(:image_classification).where(base_imagable: @asset.transam_asset)
  - if asset_images.where(image_classifications: { name: ['*Roadway Looking Ahead on Inventory', '*Elevation From Upstream (Looking X)', '*Underbridge/Superstructure']}).count > 0
    .row.form-group#recentImagesCarousel.carousel.slide
      %ol.carousel-indicators
        %li.active{data: {target: "#recentImagesCarousel", slide_to: "0"}}
        %li{data: {target: "#recentImagesCarousel", slide_to: "1"}}
        %li{data: {target: "#recentImagesCarousel", slide_to: "2"}}
      .carousel-inner
        - count = 0
        - active_set = false

        - roadway_img = asset_images.find_by(image_classifications: { name: '*Roadway Looking Ahead on Inventory' })
        - if roadway_img.present?
          .item{class: active_set ? '' : 'active'}
            = image_tag(roadway_img.image.url)
            .carousel-caption
              .h5 Roadway
          - active_set = true

        - elevation_img = asset_images.find_by(image_classifications: { name: '*Elevation From Upstream (Looking X)' })
        - if elevation_img.present?
          .item{class: active_set ? '' : 'active'}
            = image_tag(elevation_img.image.url)
            .carousel-caption
              .h5 Elevation
          - active_set = true

        - superstructure_img = asset_images.find_by(image_classifications: { name: '*Underbridge/Superstructure' })
        - if superstructure_img.present?
          .item{class: active_set ? '' : 'active'}
            = image_tag(superstructure_img.image.url)
            .carousel-caption
              .h5 Superstructure

      %a.left.carousel-control{href: "#recentImagesCarousel", role: "button", data: {slide:"prev"}}
        %span.glyphicon.glyphicon-chevron-left
      %a.right.carousel-control{href: "#recentImagesCarousel", role: "button", data: {slide:"next"}}
        %span.glyphicon.glyphicon-chevron-right
  .row
    = render 'map_thumbnail'
  .row.text-center
    #{@asset.geometry.try(:y)}, #{@asset.geometry.try(:x)}
        