config/routes.rb
Rails.application.routes.draw do

  resources :inspections do

    resources :elements do
      collection do
        post :save_quantity_changes
      end

      member do
        get :edit_comment
      end

      resources :child_elements
      resources :defects do
        member do
          get :edit_comment
        end

        resources :images
        resources :defect_locations
      end

      resources :images
    end

    resources :images

    collection do
      get 'reset'
      post 'new_search'
      get 'inspection_type_settings'
      get 'audit_export'
      get 'nbi_export'
      get 'nbe_export'
      get 'qa_qc_export'

      post 'change_inspectors'
    end

    member do
      get 'edit_inspectors'
      get 'allowed_to_finalize'
      get 'print'
    end
  end

  resources :streambed_profiles do
    resources :streambed_profile_points

    collection do
      put 'update_many'
    end
  end

  resources :roadways

  resources :roadbeds do
    member do
      post :save_vertical_clearance_changes
    end
  end
  resources :roadbed_lines, only: [:index]

  resources :processable_uploads, only: [:index, :create, :destroy] do
    member do
      get 'process_file'
    end
  end

  # JSON API #
  namespace :api do
    namespace :v1 do
      get 'reference_data' => 'references#index'
      get 'associations' => 'associations#index'
      get 'bridge_conditions' => 'bridge_conditions#index'
      get 'elements' => 'elements#index'
      get 'defects' => 'defects#index'
      get 'defect_definitions' => 'defect_definitions#index'
      get 'element_definitions' => 'element_definitions#index'

      resources :inspections, only: [:index, :update] do
        resources :images
        resources :documents
      end

      resources :bridges
      resources :culverts
      resources :highway_structures, except: [:index, :update]
      resources :highway_structures, only: [:index, :update] do
        resources :images
        resources :documents
      end
      resources :streambed_profiles

      resources :elements, only: [:index, :update] do
        resources :images
      end
      resources :defects, only: [:index, :update] do
        resources :images
      end
    end
  end

  resources :highway_maps, :only => [] do
    collection do
      get 'map'
      get 'table'
    end
  end
end

app/models/processable_upload.rb
class ProcessableUpload < ApplicationRecord
  # Callbacks
  after_initialize  :set_defaults

  belongs_to :file_status_type
  belongs_to :delayed_job

  has_one :document, :as => :documentable, dependent: :destroy
  accepts_nested_attributes_for :document

  FORM_PARAMS = [
    :class_name,
    {document_attributes: Document.allowable_params}
  ]

  def self.allowable_params
    FORM_PARAMS
  end

  def notes
    document&.description
  end

  protected

  def set_defaults
    self.file_status_type ||= FileStatusType.find_by_name('Unprocessed')
  end
end

app/controllers/processable_uploads_controller.rb
class ProcessableUploadsController < TransamController
  add_breadcrumb "Home", :root_path
  add_breadcrumb "Uploads", :processable_uploads_path

  before_action :set_processable_upload, only: [:destroy, :process_file]

  # GET /processable_uploads
  def index
    @processable_uploads = ProcessableUpload.all
  end

  # POST /processable_uploads
  def create
    @processable_upload = ProcessableUpload.new(processable_upload_params)
    @processable_upload.document.creator = current_user if @processable_upload.document
    
    if @processable_upload.save
      redirect_to processable_uploads_path, notice: 'File was successfully uploaded.'
    else
      count = view_context.pluralize(@processable_upload.errors.count, 'error')
      errors = @processable_upload.errors.full_messages.join(', ')
      msg = "#{count} prevented the file from being uploaded: #{errors}"
      redirect_to processable_uploads_path, alert: msg
    end
  end

  # DELETE /processable_uploads/1
  def destroy
    @processable_upload.destroy
    redirect_to processable_uploads_url, notice: 'Uploaded file was successfully deleted.'
  end

  # GET /processable_uploads/1/process
  def process_file
    # checks: file open, class has method
    url = @processable_upload.document.document.file.url
    ext = File.extname(url)
    klass = @processable_upload.class_name.constantize
    successful = true

    begin
      file = open(url)
    rescue OpenURI::HTTPError => e
      successful = false
      msg = e.message
    end
    
    if successful
      @processable_upload.update_attributes(file_status_type: FileStatusType.find_by(name: 'In Progress'))
      if klass.respond_to? :process_upload
        successful, msg, actual_class = klass.process_upload(file, ext)
      else
        successful = false
        msg = "Class: #{klass} does not support upload processing"
      end
    end
    if successful
      @processable_upload.update_attributes(file_status_type: FileStatusType.find_by(name: 'Complete'),
                                            class_name: actual_class)
      redirect_to processable_uploads_path, notice: 'File was successfully processed. ' + msg
    else
      @processable_upload.update_attributes(file_status_type: FileStatusType.find_by(name: 'Errored'))
      redirect_to processable_uploads_path, alert: 'Processing failed. ' + msg
    end      
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_processable_upload
      @processable_upload = ProcessableUpload.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def processable_upload_params
      params.require(:processable_upload).permit(ProcessableUpload.allowable_params)
    end
end

app/views/processable_uploads/index.html.haml
#processing-document
  = render :partial => 'shared/running_process', :locals => {:message => "Processing file. This might take a while."}
%table.table{:data => {:toggle => 'table',
  :pagination => 'true',
  :page_list => "[5, 10, 20, 50, 100]",
  :page_size => current_user.num_table_rows,
  :search => 'false'}}
  %thead
    %tr
      %th Structure Class
      %th File
      %th Size
      %th Status
      %th Notes
      %th Uploaded by
      %th Updated at
      %th Actions
  %tbody
    - @processable_uploads.each do |u|
      %tr
        %td= u.class_name
        %td= u.document.original_filename
        %td= number_to_human_size(u.document.file_size)
        %td= u.file_status_type
        %td= u.document.description
        %td= u.document.creator&.name
        %td= format_as_date_time(u.updated_at)
        %td
          = link_to 'Process', process_file_processable_upload_path(u), class: 'process_link'
          = link_to 'Delete', u, method: :delete, data: { confirm: 'Are you sure?' }
%br/
#documents
  .row
    .col-md-12
      %fieldset
        %legend Add Upload
        - @pu = ProcessableUpload.new
        - @pu.build_document
        .col-md-6
          = simple_form_for(@pu,
              :html => {:multipart => true, :class => 'form-vertical document_form' },
              :url => processable_uploads_path,
              :wrapper => :vertical_form,
              :wrapper_mappings => {:file => :vertical_file_input}) do |f|
            .col-md-4
              = f.input :class_name, label: 'Expected Structure Class', include_blank: false, collection: ['Bridge', 'Culvert']
            .row
              .col-md-12
                = f.simple_fields_for :document do |d|
                  = d.input :document, label: 'File', as: 'file', :required => true, :input_html => { :extension => "xml,zip" }
                  = d.input :description, label: 'Notes', :as => :text, :placeholder => 'Enter a brief description of the upload file...', :required => true, :input_html => { :minlength => 1, :maxlength => 254 }
            = f.submit "Add Upload", :class => 'btn btn-primary', :id => "upload_submit"

:javascript

  // Hide the processing div and show the form
  $('#processing-document').hide();
  $('#documents').show();

  $.extend(jQuery.validator.messages, {
    extension: "Please attach a file with a valid extension {0}."
  });

  // jquery validations
  $('.document_form').validate({
    ignore: [], //validate hidden fields
    submitHandler: function(form) {
      $('#processing-document').show();
      $('#documents').hide();
      form.submit();
    }
  });

  $(function () {
    $('.process_link').click(function () {
      $('#processing-document').show();
      $('#documents').hide();
    });
  });