config/routes.rb
Rails.application.routes.draw do

  resources :inspections do

    resources :elements do
      collection do
        post :save_quantity_changes
      end

      member do
        get :edit_comment
      end

      resources :child_elements
      resources :defects do
        member do
          get :edit_comment
        end

        resources :images
        resources :defect_locations
      end

      resources :images
    end

    resources :images

    collection do
      get 'reset'
      post 'new_search'
      get 'inspection_type_settings'
      get 'audit_export'
      get 'nbi_export'
      get 'nbe_export'
      get 'qa_qc_export'

      post 'change_inspectors'
    end

    member do
      get 'edit_inspectors'
      get 'allowed_to_finalize'
      get 'print'
    end
  end

  resources :streambed_profiles do
    resources :streambed_profile_points

    collection do
      put 'update_many'
    end
  end

  resources :roadways

  resources :roadbeds do
    member do
      post :save_vertical_clearance_changes
    end
  end
  resources :roadbed_lines, only: [:index]

  resources :processable_uploads, only: [:index, :create, :destroy] do
    member do
      get 'process_file'
    end
  end

  # JSON API #
  namespace :api do
    namespace :v1 do
      get 'reference_data' => 'references#index'
      get 'associations' => 'associations#index'
      get 'bridge_conditions' => 'bridge_conditions#index'
      get 'elements' => 'elements#index'
      get 'defects' => 'defects#index'
      get 'defect_definitions' => 'defect_definitions#index'
      get 'element_definitions' => 'element_definitions#index'

      resources :inspections, only: [:index, :update] do
        resources :images
        resources :documents
      end

      resources :bridges
      resources :culverts
      resources :highway_structures, except: [:index, :update]
      resources :highway_structures, only: [:index, :update] do
        resources :images
        resources :documents
      end
      resources :streambed_profiles

      resources :elements, only: [:index, :update] do
        resources :images
      end
      resources :defects, only: [:index, :update] do
        resources :images
      end
    end
  end

  resources :highway_maps, :only => [] do
    collection do
      get 'map'
      get 'table'
    end
  end
end

app/models/inspection_type.rb
class InspectionType < ApplicationRecord

  # All types that are available
  scope :active, -> { where(:active => true) }
  scope :can_be_recurring, -> { where(can_be_recurring: true) }
  scope :can_be_unscheduled, -> { where(can_be_unscheduled: true) }
  scope :not_special, -> { where.not(name: 'Special') }
  scope :special, -> { where(name: 'Special') }

  def to_s
    name
  end

end

app/controllers/api/v1/inspections_controller.rb
class Api::V1::InspectionsController < Api::ApiController

  before_action :set_paper_trail_whodunnit, only: [:update]

  # GET /inspections
  def index
    get_data

    # change inspection status from assigned to in_field
    @inspections.where(state: 'assigned').update_all(state: 'in_field')
  end

  # PUT/PATCH /inspections/:id
  def update
    @inspection = Inspection.find_by_object_key(params[:id])
    unless @inspection
      @status = :error
      @message  = "Inspection #{params[:id]} not found"
      render status: 400, json: json_response(:error, message: @message)
      return
    end

    begin
      ActiveRecord::Base.transaction do

        if params[:inspection]
          inspection_hash = params[:inspection].permit(@inspection.allowable_params).to_h
          inspection_hash[:status] = 'in_progress' if @inspection.status == 'in_field' # special case
          @inspection.update!(inspection_hash) if @inspection
        end

        if params[:bridge_condition]
          @bridge_condition = Inspection.get_typed_inspection(@inspection)
          bc_hash = params[:bridge_condition].permit(@bridge_condition.allowable_params).to_h
          @bridge_condition.update!(bc_hash) if @bridge_condition
        end

        if params[:culvert_condition]
          @culvert_condition = Inspection.get_typed_inspection(@inspection)
          cc_hash = params[:culvert_condition].permit(@culvert_condition.allowable_params).to_h
          @culvert_condition.update!(cc_hash) if @culvert_condition
        end

        if params[:ancillary_condition]
          @ancillary_condition = Inspection.get_typed_inspection(@inspection)
          ac_hash = params[:ancillary_condition].permit(@ancillary_condition.allowable_params).to_h
          @ancillary_condition.update!(ac_hash) if @ancillary_condition
        end

        if params[:structure]
          @structure = TransamAsset.get_typed_asset(@inspection.highway_structure)
          structure_hash = params[:structure].permit(@structure.allowable_params).to_h
          # Don't allow asset_subtype_id changes that would change asset_type
          if structure_hash.include? :asset_subtype_id
            unless @structure.asset_type == AssetSubtype.find(structure_hash[:asset_subtype_id]).asset_type
              @struct_asset_type_must_match = true
              raise ActiveRecord::Rollback
            end
          end
          @structure&.update!(structure_hash)
        end

        if params[:elements] && params[:elements].any?
          params[:elements].each do |el_params|
            change_type = el_params[:change_type]&.upcase

            clean_params = el_params.permit(Element.allowable_params).to_h
            el_guid = el_params[:id]
            if el_params[:parent_id]
              el_parent = Element.find_by_guid(el_params[:parent_id])
            end

            case change_type
            when 'ADD', 'UPDATE'
              el = Element.find_by_guid(el_guid)
              clean_params[:parent] = el_parent if el_parent
              clean_params[:inspection] = @inspection
              if el
                el.update!(clean_params)
              else
                if el_guid.blank?
                  @el_guid_required_to_add = true
                  raise ActiveRecord::Rollback
                end
                clean_params["guid"] = el_guid
                Element.create!(clean_params)
              end
            when 'REMOVE'
              el = Element.find_by_guid(el_guid)
              el.destroy! if el
            end
          end
        end

        if params[:defects] && params[:defects].any?
          params[:defects].each do |df_params|
            change_type = df_params[:change_type]&.upcase

            clean_params = df_params.permit(Defect.allowable_params).to_h
            df_guid = df_params[:id]
            if df_params[:element_id]
              el_parent = Element.find_by_guid(df_params[:element_id])
            end

            case change_type
            when 'ADD', 'UPDATE'
              el = Defect.find_by_guid(df_guid)
              clean_params[:element] = el_parent if el_parent
              clean_params[:inspection] = @inspection
              if el
                el.update!(clean_params)
              else
                if df_guid.blank?
                  @df_guid_required_to_add = true
                  raise ActiveRecord::Rollback
                end
                clean_params["guid"] = df_guid
                Defect.create!(clean_params)
              end
            when 'REMOVE'
              el = Defect.find_by_guid(df_guid)
              el.destroy! if el
            end
          end
        end

        if params[:defect_locations] && params[:defect_locations].any?
          params[:defect_locations].each do |dl_params|
            change_type = dl_params[:change_type]&.upcase

            clean_params = dl_params.permit(DefectLocation.allowable_params).to_h
            dl_guid = dl_params[:id]
            if dl_params[:defect_id]
              dl_parent = Defect.find_by_guid(dl_params[:defect_id])
            end

            case change_type
            when 'ADD', 'UPDATE'
              dl = DefectLocation.find_by_guid(dl_guid)
              clean_params[:defect] = dl_parent if dl_parent
              if dl
                dl.update!(clean_params)
              else
                if dl_guid.blank?
                  @dl_guid_required_to_add = true
                  raise ActiveRecord::Rollback
                end
                clean_params["guid"] = dl_guid
                DefectLocation.create!(clean_params)
              end
            when 'REMOVE'
              dl = DefectLocation.find_by_guid(dl_guid)
              dl.destroy! if dl
            end
          end
        end

        if params[:streambed_profiles] && params[:streambed_profiles].any?
          params[:streambed_profiles].each do |sp_params|
            change_type = sp_params[:change_type]&.upcase

            clean_params = sp_params.permit(sp_params.keys).except(:id, :highway_structure_id, :inspection_id, :change_type).to_h
            sp_guid = sp_params[:id]
            if sp_params[:highway_structure_id]
              sp_parent = HighwayStructure.find_by(guid: sp_params[:highway_structure_id])
            end
            if sp_params[:inspection_id]
              sp_inspection = Inspection.find_by(guid: sp_params[:inspection_id])
            end

            case change_type
            when 'ADD', 'UPDATE'
              sp = StreambedProfile.find_by_guid(sp_guid)
              clean_params[:transam_asset_id] = sp_parent.id if sp_parent
              clean_params[:inspection_id] = sp_inspection.id if sp_inspection
              if sp
                sp.update!(clean_params)
              else
                if sp_guid.blank?
                  @sp_guid_required_to_add = true
                  raise ActiveRecord::Rollback
                end
                clean_params["guid"] = sp_guid
                clean_params[:is_from_api] = true
                StreambedProfile.create!(clean_params)
              end
            when 'REMOVE'
              sp = StreambedProfile.find_by_guid(sp_guid)
              sp.destroy! if sp
            end
          end
        end

        if params[:streambed_profile_points] && params[:streambed_profile_points].any?
          params[:streambed_profile_points].each do |spp_params|
            change_type = spp_params[:change_type]&.upcase

            clean_params = spp_params.permit(spp_params.keys).except(:id, :profile_id, :change_type).to_h
            spp_guid = spp_params[:id]
            if spp_params[:profile_id]
              spp_parent = StreambedProfile.find_by_guid(spp_params[:profile_id])
            end

            case change_type
            when 'ADD', 'UPDATE'
              spp = StreambedProfilePoint.find_by_guid(spp_guid)
              clean_params[:streambed_profile] = spp_parent if spp_parent
              if spp
                spp.update!(clean_params)
              else
                if spp_guid.blank?
                  @spp_guid_required_to_add = true
                  raise ActiveRecord::Rollback
                end
                clean_params["guid"] = spp_guid
                StreambedProfilePoint.create!(clean_params)
              end
            when 'REMOVE'
              spp = StreambedProfilePoint.find_by_guid(spp_guid)
              spp.destroy! if spp
            end
          end
        end

        if params[:roadbeds] && params[:roadbeds].any?
          params[:roadbeds].each do |rb_params|
            change_type = rb_params[:change_type]&.upcase

            clean_params = rb_params.permit(rb_params.keys).except(:id, :roadway_id, :change_type).to_h
            rb_guid = rb_params[:id]
            if rb_params[:roadway_id]
              rb_parent = Roadway.find_by_guid(rb_params[:roadway_id])
            end

            case change_type
            when 'ADD', 'UPDATE'
              rb = Roadbed.find_by_guid(rb_guid)
              clean_params[:roadway] = rb_parent if rb_parent
              clean_params[:inspection] = @inspection
              if rb
                rb.update!(clean_params)
              else
                if rb_guid.blank?
                  @rb_guid_required_to_add = true
                  raise ActiveRecord::Rollback
                end

                clean_params["guid"] = rb_guid
                Roadbed.create!(clean_params)
              end
            when 'REMOVE'
              rb = Roadbed.find_by_guid(rb_guid)
              rb.destroy! if rb
            end
          end
        end

        if params[:roadbed_lines] && params[:roadbed_lines].any?
          params[:roadbed_lines].each do |rbl_params|
            change_type = rbl_params[:change_type]&.upcase

app/views/inspections/_actions.html.haml
- allowable_events = @inspection.allowable_event_objects

.btn-group.pull-right.panel-action.inspection-action-button
  %button.btn.btn-primary.btn-sm.dropdown-toggle{:data => {:toggle => 'dropdown'}}
    %i.fa.fa-cog
    = " Actions"
    %span.caret
  %ul.dropdown-menu.inspection-action-menu{:role => 'menu'}
    - allowable_events.each do |evt|
      - if (can? evt.name.to_sym, @inspection.inspection)
        %li
          = link_to fire_workflow_event_transam_workflow_index_path(:class_name => 'Inspection', :object_key => @inspection.object_key, :event_name => evt.name) do
            %i.fa.fa-fw{:class => @inspection.get_workflow_event_icon(evt.name)}
            = evt.human_name
    - if @inspection.state == 'ready' && (can? :reopen, @inspection.inspection) && !(allowable_events.map{|x| x.name}.include? 'reopen')
      %li
        = link_to fire_workflow_event_transam_workflow_index_path(transam_workflow_model_proxy: {include_updates: 1, event_name: 'reopen', global_ids: [@inspection.inspection.to_global_id], assigned_organization_id: nil}) do
          %i.fa.fa-fw{:class => @inspection.get_workflow_event_icon('reopen')}
          To Open
    - elsif @inspection.state == 'signature_ready' && !(allowable_events.map{|x| x.name}.include? 'finalize')
      %li
        = link_to allowed_to_finalize_inspection_path(@inspection.object_key), remote: true do
          %i.fa.fa-fw{:class => @inspection.get_workflow_event_icon('finalize')}
          To Final

:javascript
  $(document).ready(function() {
    if ($('ul.inspection-action-menu li').length > 0) {
      $('.inspection-action-button').show();
    } else {
      $('.inspection-action-button').hide();
    }
  });

app/views/inspections/_child_element_row_action_buttons.html.haml
:ruby
  parent_element = element.parent
.dropdown
  %button.btn.btn-sm.dropdown-toggle.element_defect_row_action_button{:data => {:toggle => 'dropdown'}}
    .fa.fa-ellipsis-h
  %ul.dropdown-menu.dropdown-menu-right{:role => 'menu'}
    %li.text-left
      = link_to edit_inspection_element_child_element_path(parent_element.inspection, parent_element, element), remote: true do
        = "Edit Protective System"
    %li.text-left
      = link_to new_inspection_element_defect_path(parent_element.inspection, element), remote: true do
        = "Add Defect"
    - if can? :create, element.images.build
      %li.text-left
        = link_to new_inspection_element_image_path(parent_element.inspection, element, form_view: 'elements/photo_form'), :remote => true do
          Add Photo
    %li.text-left
      = link_to edit_comment_inspection_element_path(parent_element.inspection, element), remote: true do
        = "Edit Comment"
    %li.text-left
      = link_to inspection_element_child_element_path(parent_element.inspection, parent_element, element), remote: true, method: :delete, data: { confirm: 'Are you sure?', dismiss: "modal" }  do
        = "Delete"

app/views/inspections/_defect_row_action_buttons.html.haml
.dropdown
  %button.btn.btn-sm.dropdown-toggle.element_defect_row_action_button{:data => {:toggle => 'dropdown'}}
    .fa.fa-ellipsis-h
  %ul.dropdown-menu.dropdown-menu-right{:role => 'menu'}
    %li.text-left
      = link_to edit_inspection_element_defect_path(defect.inspection, defect.element, defect), remote: true do
        = "Edit Defect"
    %li.text-left
      = link_to inspection_element_defect_path(defect.inspection, defect.element, defect), remote: true, method: :delete, data: { confirm: 'Are you sure?', dismiss: 'modal' }  do
        = "Delete"

app/views/inspections/_inspections_table.html.haml
:css
  .popover-title{
      background: #fbf381;
  }
  .popover-action:hover {
    cursor: pointer;
    cursor: hand;
  }
  .clear-inspection-selections {
    cursor: pointer;
    color: red;
    padding-left: 5px;
  }
  .bs-bars.pull-left {
    float: none !important;
    display: inline-block;
    width: 91%;
  }
  .dropdown-menu > li > form > button {
  display: block;
  padding: 3px 20px;
  clear: both;
  font-weight: 400;
  line-height: 1.428571429;
  }

#inspection_table_actions.btn-toolbar
  %span.col-sm-6
    %b#selected_inspection_count
    %i.fa.fa-close.clear-inspection-selections{style: 'display: none;', title: 'Clear selections.'}
  .navbar-form.pull-right{:style => 'margin: 0px;'}
    %button.btn.btn-primary.btn-md.dropdown-toggle{:data => {:toggle => 'dropdown'}, :style => 'vertical-align: top;'}
      %i.fa.fa-file
      = " Export"
      %span.caret
    %ul.dropdown-menu{:role => 'menu', :style => 'padding-top: 0px;'}
      %li{:style => "background-color: #f5f5f5; padding-left: 20px;  border-bottom: 1px solid black;"}
        Export for NBI/NBE
      %li{:style => 'border-bottom: 1px solid black;'}
        = link_to 'TXT', nbi_export_inspections_path, title: 'Export filtered structures to NBI TXT'
      %li{:style => 'border-bottom: 1px solid black;'}
        = link_to 'XML', nbe_export_inspections_path(format: :xml), title: 'Export filtered structures to NBE XML'
      %li{:style => "background-color: #f5f5f5; padding-left: 20px; padding-right: 20px; border-bottom: 1px solid black; border-top: 1px solid black"}
        Export for QA/QC
      %li
        = link_to 'XML', qa_qc_export_inspections_path(format: :xml), id: 'qa_qc_export_link', title: 'Export selected structures to QA/QC XML'
.table-responsive
  %table.table.table-condensed.table-hover{:id => "inspection-table",
    :data => {:toggle => 'table',
    :card_view => "false",
    :pagination => 'true',
    :url => inspections_path(:format => :json),
    :side_pagination => 'server',
    :show_pagination_switch => 'false',
    :page_number => '1',
    :page_list => "[5, 10, 20, 50, 100, 500, 1000]",
    :page_size => current_user.num_table_rows,
    :sortable => 'true',
    :sort_order => 'asc',
    :sort_name => 'object_key',
    :cookie => 'true',
    :cookie_id_table => "inspections_table_id",
    :cookie_expire => "1d",
    :search => 'false',
    :toolbar => "#inspection_table_actions",
    :show_columns => 'true',
    :show_export => 'true',
    :export_types => "['csv', 'txt', 'excel']",
    :id_field => 'object_key',
    :resizable => 'true',
    :maintain_selected => 'true',
    :single_select => 'false'}}
    %thead
      %tr
        %th.center{:data => {:field => 'dummy1', :formatter => 'inspection_link_formatter'}}
        %th.center{:data => {:field => 'checked', :checkbox => 'true'}} Selected
        %th.center{:data => {:field => 'to_global_id', :visible => 'false'}} Global ID
        %th.center{:data => {:field => 'highway_structurible_type', :sortable => 'true'}}= reference_label('highway_structures', 'highway_structurible_type', 'Structure Class')
        %th.center{:data => {:field => 'organization_type', :sortable => 'true'}}= reference_label('inspections', 'organization_type_id', 'Inspection Group')
        %th.center{:data => {:field => 'assigned_organization', :sortable => 'true'}}= reference_label('inspections', 'assigned_organization_id', 'Inspection Team')
        %th.center{:data => {:field => 'inspectors', :sortable => 'false'}}= reference_label('inspections', 'inspectors', 'Inspectors')
        %th.center{:data => {:field => 'inspection_trip', :sortable => 'true'}}= reference_label('inspections', 'inspection_trip', 'Inspection Trip')
        %th.center{:data => {:field => 'calculated_inspection_due_date', :sortable => 'true', :formatter => "month_year_formatter"}}= reference_label('inspections', 'calculated_inspection_due_date', 'Due Date')
        %th.center{:data => {:field => 'event_datetime', :sortable => 'true', :formatter => "date_formatter"}}= reference_label('inspections', 'event_datetime', 'Inspection Date')
        %th.center{:data => {:field => 'transam_assets_asset_tag', :sortable => 'true', :formatter => 'structure_link_formatter'}}= reference_label('highway_structures', 'transam_assets.asset_tag', 'Structure Key')
        %th.center.hidden{:data => {:field => 'object_key', :sortable => 'true'}} Inspection Key
        %th.center{:data => {:field => 'inspection_category', :sortable => 'false'}}= reference_label('highway_structures', 'inspection_category_id', 'Inspection Category')
        %th.center{:data => {:field => 'inspection_type', :sortable => 'true'}}= reference_label('inspections', 'inspection_category_type_id', 'Inspection Type')
        %th.center{:data => {:field => 'state', :sortable => 'true'}}= reference_label('inspections', 'state', 'Inspection Status')
        %th.center{:data => {:field => 'location_description', :sortable => 'true'}}= reference_label('highway_structures', 'location_description', 'Location Description')
        %th.center{:data => {:field => 'owner', :sortable => 'true'}}= reference_label('highway_structures', 'owner_id', 'Owner')
        %th.center{:data => {:field => 'calculated_condition', :sortable => 'false'}}= reference_label('highway_structures', 'calculated_condition', 'Condition')
        %th.center{:data => {:field => 'inspection_program', :sortable => 'true'}}= reference_label('highway_structures', 'inspection_program_id', 'Inspection Program')
        /%th.center{:data => {:field => 'inspection_zone', :sortable => 'true'}}= reference_label('inspections', 'inspection_zone_id', 'Inspection Zone')
        %th.center{:data => {:field => 'routine_report_submitted_at', :sortable => 'true', :formatter => "date_formatter"}}= reference_label('inspections', 'routine_report_submitted_at', 'Routine Inspection Submitted')

= render 'shared/table_formatters'

:javascript
  var selected_rows = new Set();

  // stub correct sorting field name
  var inspection_search_sorting_mappings = {
    transam_assets_asset_tag: "transam_assets.asset_tag",
    highway_structurible_type: "asset_types.class_name",
    location_description: "highway_structures.location_description",
    owner: "owners.code",
    //calculated_condition: "inspections.calculated_condition",
    assigned_organization: "assigned_organizations.name",
    organization_type: "organization_types.name",
    inspection_program: "inspection_programs.name",
    inspection_type: "inspection_types.name",
    inspection_trip: "inspections.inspection_trip"
  };

  $('#inspection-table').bootstrapTable({
    onLoadError: function(status, res) {
      alert('An error occurred loading your search results. Please refresh the page and try your search again.');
    },
    queryParams: function(params) {
      params.sort = params.sort || params.sortName;
      params.order = params.order || params.sortOrder;
      var sort_field = params.sort;
      var map_field = inspection_search_sorting_mappings[sort_field];
      if(map_field) {
        params.sort = map_field;
      }

      return params;
    }
  });

  function month_year_formatter(value) {
    if (value) {
      return moment(value).format('MMM YYYY');
    } else {
      return value;
    }
  }

  // more table formatters
  function structure_link_formatter(value, row) {
    if (value == null) {
      return "-";
    } else {
      return '<a target="_blank" href="/inventory/' + row['structure_object_key'] + '">' + value + '</a>';
    }
  }

  function inspection_link_formatter(value, row) {
    return '<a href="/inspections/' + row['object_key'] + '">View</a>';
  }

  $(document).ready(function() {
    // Initialize popovers
    $('[data-toggle="popover"]').popover();

    // Enables or disables the package actions depending on how many are selected
    function enable_disable_table_actions() {
      enable_disable_change_workflow();
      enable_disable_change_inspectors();
    }

    $('.clear-inspection-selections').on('click', function() {
      selected_rows = new Set();
      $('#inspection-table').bootstrapTable('uncheckAll');
      $('#inspection-table tr.selected').removeClass('selected');
    });

    // Updates the selected rows in the table
    function add_rows(rows) {
      for (i = 0; i < rows.length; i++) {
        var insp_key = rows[i].to_global_id;
        if(!selected_rows.has(insp_key)) {
          selected_rows.add(insp_key);
        }
      }

      update_selection_count_text();
      update_qa_qc_params();
      enable_disable_table_actions();
    }

    function remove_rows(rows) {
      for (i = 0; i < rows.length; i++) {
        var insp_key = rows[i].to_global_id;
        if(selected_rows.has(insp_key)) {
          selected_rows.delete(insp_key);
        }
      }

      update_selection_count_text();
      update_qa_qc_params();
      enable_disable_table_actions();
    }

    function update_selection_count_text() {
      if(selected_rows.size > 0) {
        $('#selected_inspection_count').text(selected_rows.size + " inspection records selected.");
        $('.clear-inspection-selections').show();
      } else {
        $('#selected_inspection_count').text("");
        $('.clear-inspection-selections').hide();
      }
    }

    function update_qa_qc_params() {
      base_url = $('#qa_qc_export_link').attr('href').split('?')[0]
      if(selected_rows.size > 0) {
        $('#qa_qc_export_link').attr('href', base_url + '?global_ids=' + Array.from(selected_rows))
      } else {
        $('#qa_qc_export_link').attr('href', base_url)
      }
    }

    function check_row_selected() {
      $("#inspection-table").bootstrapTable("checkBy", {field:"to_global_id", values: Array.from(selected_rows)})
    }

    $('#inspection-table').on('check.bs.table', function(row, elem) {
      add_rows([elem]);
    }).on('uncheck.bs.table', function(row, elem) {
      remove_rows([elem]);
    }).on('check-all.bs.table', function(rows, elements) {
      add_rows(elements);
    }).on('uncheck-all.bs.table', function(rows, elements) {
      remove_rows(elements);
    }).on('page-change.bs.table', function(page_number, page_size) {
      check_row_selected();
    }).on('load-success.bs.table', function(data) {
      check_row_selected();
    }).on('all.bs.table', function(e, row) {
      $('[data-toggle="popover"]').popover();
    });

  });
  $(window).resize(function() {
    $('#inspection-table').bootstrapTable('resetView');
  });

app/views/inspections/_maintenance_recommendations.html.haml
.row
  %span.col-xs-1
    Priority
  %span.col-xs-1
    Status
  %span.col-xs-1
    General Location
  %span.col-xs-2
    Recommendations
  %span.col-xs-1
    Inspection Notes
  %span.col-xs-3
    Date Furst Recommended
  %span.col-xs-1
    Timeline
  %span.col-xs-1
    Date Completed
.row
  %span.col-xs-1
    Priority
  %span.col-xs-1
    Status
  %span.col-xs-1
    General Location
  %span.col-xs-2
    Recommendations
  %span.col-xs-1
    Inspection Notes
  %span.col-xs-3
    Date Furst Recommended
  %span.col-xs-1
    Timeline
  %span.col-xs-1
    Date Completed

app/views/inspections/_photo_form.html.haml
PENDING

app/views/inspections/_roadbed.html.haml
%legend
  Roadbed Table

.row
  .col-sm-6{style: 'border-right: 1px solid #17406E;'}
    - roadways = @inspection.highway_structure.roadways
    - roadbeds = Roadbed.where(roadway: roadways, inspection: @inspection).order(:name, :direction)
    .col-sm-6
      = select_tag :roadway_id, options_from_collection_for_select(@inspection.highway_structure.roadways, "object_key", "to_s"), "data-remote" => 'true', "data-url" => roadbeds_path(inspection_id: @inspection.object_key), include_blank: "All Roadways", class: 'form-control'
    - if can?(:manage, Roadway) && can?(:update, @inspection.inspection) && @inspection.updatable? && @inspection.highway_structure.roadways.any?
      .pull-right
        = link_to new_roadbed_path(inspection_id: @inspection.object_key), remote: true, id: "new_roadbed_link", class: 'btn btn-primary add-roadbed', title: 'Add Roadbed' do
          %i.fa.fa-plus
          = " Add Roadbed"

    .col-sm-12{style: 'padding-top: 10px;'}
      .table-responsive#roadbeds_table_container
        = render 'roadbeds/roadbeds_table', roadbeds: roadbeds, inspection: @inspection
  
  .col-sm-6
    - roadbed = roadbeds.first
    .col-sm-6
      = render 'roadbeds/roadbed_dropdown', roadbeds: roadbeds, selected: roadbed
    .col-sm-12{style: 'padding-top: 10px;'}
      .table-responsive#roadbed_lines_table_container
        = render 'roadbed_lines/roadbed_lines_table', roadbed: roadbed

app/views/inspections/allowed_to_finalize.js.haml
$('#form-modal').html("#{escape_javascript(render 'inspections/allowed_to_finalize_modal')}");
$('#form-modal').modal('show');

app/views/inspections/bridge_inspection.pdf.haml
.document
  .col-xs-12
    .row
      %span.col-xs-2.pdf_header_image
      = wicked_pdf_image_tag "nyc_dot.jpg", alt: 'New York City DOT', :style => 'width: 160px; height: 70px; float:left'

app/views/inspections/edit.js.haml
$('#form-modal').html("#{escape_javascript(render 'inspections/edit_form')}");
$('#form-modal').modal('show');

app/views/inspections/inspection_type_settings.js.haml
- if @asset
  $('#form-modal').html("#{escape_javascript(render 'inspections/inspection_schedule_form')}");
  $('#form-modal').modal('show');